apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rgd1eikjj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rgd1eikjj-go 
  name: rgd1eikjj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rgd1eikjj-go 
